// Code generated by mockery v1.0.0. DO NOT EDIT.

package utils

import mock "github.com/stretchr/testify/mock"

// MockHasHTTPStatus is an autogenerated mock type for the HasHTTPStatus type
type MockHasHTTPStatus struct {
	mock.Mock
}

// GetErrorType provides a mock function with given fields:
func (_m *MockHasHTTPStatus) GetErrorType() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetHTTPStatusCode provides a mock function with given fields:
func (_m *MockHasHTTPStatus) GetHTTPStatusCode() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
