// Code generated by mockery v1.0.0. DO NOT EDIT.

package api

import echo "github.com/labstack/echo"
import mock "github.com/stretchr/testify/mock"

// MockRouter is an autogenerated mock type for the Router type
type MockRouter struct {
	mock.Mock
}

// Health provides a mock function with given fields: _a0
func (_m *MockRouter) Health(_a0 echo.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Index provides a mock function with given fields: _a0
func (_m *MockRouter) Index(_a0 echo.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Shutdown provides a mock function with given fields:
func (_m *MockRouter) Shutdown() {
	_m.Called()
}

// Start provides a mock function with given fields: address
func (_m *MockRouter) Start(address string) error {
	ret := _m.Called(address)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(address)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
